CREATE DATABASE IF NOT EXISTS hospital;
USE hospital;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	fullName VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS specialists (
	id INT AUTO_INCREMENT PRIMARY KEY,
	specialistName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS doctors (
	id INT AUTO_INCREMENT PRIMARY KEY,
	fullName VARCHAR(100) NOT NULL,
	dob VARCHAR(100) NOT NULL,
	qualification VARCHAR(100) NOT NULL,
	specialist VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	mobNo VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS appointments (
	id INT AUTO_INCREMENT PRIMARY KEY,
	userId INT NOT NULL,
	fullName VARCHAR(100) NOT NULL,
	gender VARCHAR(100) NOT NULL,
	age VARCHAR(100) NOT NULL,
	appointmentDate VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(100) NOT NULL,
	diseases VARCHAR(100) NOT NULL,
	doctorId INT NOT NULL,
	address VARCHAR(100) NOT NULL,
	status VARCHAR(100) NOT NULL,
	FOREIGN KEY (userId) REFERENCES users(id),
	FOREIGN KEY (doctorId) REFERENCES doctors(id)
);



